# Generated by Django 2.2.2 on 2019-07-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tabel_produk',
            fields=[
                ('kode_produk', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('nama_produk', models.CharField(max_length=200)),
                ('stok_produk', models.IntegerField()),
                ('desc_produk', models.TextField()),
                ('harga_produk', models.CharField(max_length=200)),
            ],
        ),
    ]
