# Generated by Django 2.2.4 on 2019-08-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabel_produk',
            name='foto_produk',
            field=models.FileField(default=0, upload_to='images/'),
        ),
    ]
