# Generated by Django 2.2.4 on 2019-08-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tabel_produk_foto_produk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabel_produk',
            name='foto_produk',
            field=models.FileField(upload_to='images/'),
        ),
    ]
