# Generated by Django 2.2.4 on 2019-08-02 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tabel_produk_uang_produk'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tabel_produk',
            new_name='ss_produk',
        ),
    ]
