# Generated by Django 2.2.4 on 2019-08-02 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190802_1359'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ss_produk',
            new_name='tabel_produk',
        ),
    ]
