# Generated by Django 2.2.4 on 2019-08-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190802_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='ss_produk',
            fields=[
                ('kode_produk', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('nama_produk', models.CharField(max_length=200)),
                ('stok_produk', models.IntegerField()),
                ('desc_produk', models.TextField()),
                ('harga_produk', models.CharField(max_length=200)),
                ('foto_produk', models.FileField(upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='tabel_produk',
            name='uang_produk',
        ),
    ]
