# Generated by Django 2.2.4 on 2019-08-02 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190802_1402'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ss_produk',
        ),
    ]
